# Generated by Django 4.2.5 on 2023-09-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controle_disciplina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlunoEntity',
            new_name='StudentEntity',
        ),
        migrations.RenameModel(
            old_name='DisciplinaEntity',
            new_name='SubjectEntity',
        ),
        migrations.RenameModel(
            old_name='TarefaEntity',
            new_name='TaskEntity',
        ),
        migrations.RenameField(
            model_name='studententity',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subjectentity',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='subjectentity',
            old_name='nome',
            new_name='name',
        ),
    ]
