# Generated by Django 4.2.5 on 2023-09-21 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controle_disciplina', '0002_rename_alunoentity_studententity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskentity',
            old_name='concluida',
            new_name='concluded',
        ),
        migrations.RenameField(
            model_name='taskentity',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='taskentity',
            old_name='data_entrega',
            new_name='submit_homework',
        ),
        migrations.RenameField(
            model_name='taskentity',
            old_name='tarefa_aluno',
            new_name='task_student',
        ),
        migrations.RenameField(
            model_name='taskentity',
            old_name='tarefa_disciplina',
            new_name='task_subject',
        ),
        migrations.RenameField(
            model_name='taskentity',
            old_name='titulo',
            new_name='title',
        ),
    ]
